# Generated by Django 5.0.1 on 2024-01-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_subplan_subplanfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subplanfeature',
            name='subplan',
        ),
        migrations.AddField(
            model_name='subplanfeature',
            name='subplan',
            field=models.ManyToManyField(to='main.subplan'),
        ),
    ]
