# Generated by Django 5.0.1 on 2024-02-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_trainerachivement'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
