# Generated by Django 5.0.1 on 2024-02-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_trainersalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainersalary',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
